name: Calculate Time Since Issue Assignment

on:
  pull_request:
    types:
      - opened

jobs:
  calculate-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Pull Request Data
        id: pr_data
        run: |
          echo "::set-output name=pr_body::$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)"
          echo "::set-output name=pr_created_at::$(jq -r '.pull_request.created_at' $GITHUB_EVENT_PATH)"

      - name: Extract Issue ID
        id: extract_issue_id
        run: |
          ISSUE_ID=$(echo "${{ steps.pr_data.outputs.pr_body }}" | grep -oP '(?<=closes #)\d+')
          echo "::set-output name=issue_id::$ISSUE_ID"

      - name: Fetch Issue Assignment Event
        id: issue_assignment
        run: |
          if [ -z "${{ steps.extract_issue_id.outputs.issue_id }}" ]; then
            echo "No issue linked. Skipping."
            exit 0
          fi
          curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.extract_issue_id.outputs.issue_id }}/events" > events.json
          
          # Trova il primo evento "assigned"
          ASSIGNED_AT=$(jq -r '[.[] | select(.event == "assigned")] | first | .created_at // empty' events.json)
          
          if [ -z "$ASSIGNED_AT" ]; then
            echo "No assignment event found. Skipping."
            exit 0
          fi

          echo "::set-output name=assigned_at::$ASSIGNED_AT"

      - name: Calculate Time Difference
        id: time_difference
        run: |
          if [ -z "${{ steps.issue_assignment.outputs.assigned_at }}" ]; then
            echo "No assignment date available. Skipping."
            exit 0
          fi
          ASSIGNED_AT="${{ steps.issue_assignment.outputs.assigned_at }}"
          PR_CREATED_AT="${{ steps.pr_data.outputs.pr_created_at }}"

          ASSIGNED_TIMESTAMP=$(date -d "$ASSIGNED_AT" +%s)
          PR_TIMESTAMP=$(date -d "$PR_CREATED_AT" +%s)

          TIME_DIFF=$((PR_TIMESTAMP - ASSIGNED_TIMESTAMP))
          echo "::set-output name=time_difference_seconds::$TIME_DIFF"

      - name: Output Time Difference
        run: |
          if [ -z "${{ steps.time_difference.outputs.time_difference_seconds }}" ]; then
            echo "Time difference could not be calculated."
            exit 0
          fi
          SECONDS=${{ steps.time_difference.outputs.time_difference_seconds }}
          echo "Time elapsed since issue was assigned to pull request creation: $SECONDS seconds."
